services:
  redis:
    image: redis:8.4.2-alpine
    container_name: medication_redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    ports:
      - "${REDIS_PUBLISHED_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - redis_data:/data
    networks:
      - medication-network

  postgres:
    image: postgres:18-alpine
    container_name: medication_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-k_med}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-MedAdmin123#}
      - POSTGRES_DB=${POSTGRES_DB:-med_sys}
    ports:
      - "${POSTGRES_PUBLISHED_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medication-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medication_api
    environment:
      - APP_NAME=${APP_NAME}
      - API_PORT=${API_PORT}
      - DB_HOST=postgres
      - DB_PORT=${POSTGRES_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - REDIS_URL=redis:6379
    ports:
      - "${API_PUBLISHED_PORT:-5010}:${API_PORT:-5010}"
    volumes:
      - ./:/app # syncs source code between host and container
      - /app/bin # Keeps Air's build artifacts inside the container
      - /app/.cache # Speeds up Go recompilation
    depends_on:
      - redis
      - postgres
    networks:
      - medication-network

volumes:
  redis_data:
  postgres_data:

networks:
  medication-network: